# Generated by Django 2.1.5 on 2019-01-25 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VariantProperties',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property', models.CharField(max_length=255)),
                ('value', models.CharField(max_length=255)),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='items.Variant')),
            ],
        ),
        migrations.RemoveField(
            model_name='varientproperties',
            name='variant',
        ),
        migrations.DeleteModel(
            name='VarientProperties',
        ),
    ]
