# Generated by Django 2.1.5 on 2019-01-25 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0005_auto_20190125_1021'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemchangelog',
            name='is_variant',
        ),
        migrations.AddField(
            model_name='itemchangelog',
            name='variant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='items.Variant'),
        ),
    ]
