# Generated by Django 2.1.5 on 2019-01-25 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0007_variantpropery_is_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='variantchangelog',
            old_name='is_property',
            new_name='is_property_change',
        ),
        migrations.AddField(
            model_name='variantchangelog',
            name='property',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='items.VariantPropery'),
        ),
    ]
