# Generated by Django 2.1.5 on 2019-01-25 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0008_auto_20190125_1108'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='VariantPropery',
            new_name='VariantProperty',
        ),
    ]
