# Generated by Django 2.1.5 on 2019-01-25 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0009_auto_20190125_1111'),
    ]

    operations = [
        migrations.AddField(
            model_name='variantchangelog',
            name='item',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='items.Item'),
            preserve_default=False,
        ),
    ]
